#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server

if [ "$#" -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

if [ ! -f "$PATH_TO_FILE" ]; then
    echo "Error: File '$PATH_TO_FILE' does not exist."
    exit 1
fi

scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~/


if [ $? -eq 0 ]; then
    echo "File '$PATH_TO_FILE' successfully transferred to $USERNAME@$IP:~/"
else
    echo "Error: Failed to transfer file."
fi
