#!/usr/bin/env bash
#Bash script to install nginx on my server

sudo apt update -y
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
echo "Nginx installed successfully"
