#!/usr/bin/env bash
# Bash script to install nginx on my server

# Update package list and install Nginx
sudo apt update -y
sudo apt install -y nginx

# Create a custom Index page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# To cause the redirection
sudo sed -i '/listen 80 default_server;/a \     rewrite ^/redirect_me https://www.google.com permanent;' /etc/nginx/sites-available/default
#string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com permanent;"
#sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-available/default

# To create a symbolic link between sites-available/default and sites-enabled/default
#sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
echo "Nginx installed successfully"
