#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page
#This custom page contains the string "Ceci n'est pas une page"

#Update Bash script and install Nginx
sudo apt update -y
sudo apt install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

sudo sed -i '/listen 80 default_server;/a \	rewrite ^/redirect_me https://www.google.com permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a \	error_page 404 /custom_404.html\n location = /custom_404.html; {\n	 internal;\n	}' /etc/nginx/sites-available/default
#To create a symbolic link between sites-available/default and sites-enabled/default
#sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart
