#!/usr/bin/env bash
# Double the number of webservers

# Update package list and install Nginx
sudo apt update -y
sudo apt install -y nginx

# Get the hostname of the server
HOSTNAME=$(hostname)

# Create a custom index page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Add rewrite rule and custom 404 error page configuration to default server block
sudo sed -i '/listen 80 default_server;/a \    add_header X-Served-By '"$HOSTNAME"';' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a \    rewrite ^/redirect_me https://www.google.com permanent;' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a \    error_page 404 /custom_404.html;\n    location = /custom_404.html {\n        internal;\n    }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx

# Confirm installation success
echo "Nginx installed and configured successfully with custom header: X-Served-By: $HOSTNAME"
