#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Update packages
sudo apt update -y
sudo apt install haproxy -y

# To enable HAproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
my_server_config=\
"
frontend haproxy-main
	bind *:80
	option forwardfor
	default_backend nginx_servers

backend nginx_servers
	balance roundrobin
	server 480982-web-01 54.172.199.131:80 check
	server 480982-web-02 54.237.57.219:80 check
"

echo "$my_server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
service haproxy restart
